name: Production Deploy
run-name: ${{ github.actor}} is building graveyardjs
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3 # reads the repo 

      # TODO: add a build step here
      - name: Install Deno
        uses: maximousblk/setup-deno@v2.0.0

      - name: Generate Prisma Client
        run: deno task generate-client

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "graveyardjs"
          entrypoint: "./main.ts" # TODO: update entrypoint
